# network architecture
# encoder related
etype: blstmp     # encoder architecture type
elayers: 4
eunits: 1024
eprojs: 1024
subsample: "3_1_1_1_1" # skip every n frame from input to nth layers
# decoder related
dlayers: 1
dunits: 1024
# attention related
atype: location
adim: 1024
awin: 5
aheads: 4
aconv-chans: 10
aconv-filts: 100

# hybrid CTC/attention
mtlalpha: 0.0

# label smoothing
lsm-type: unigram
lsm-weight: 0.06

# minibatch related
batch-size: 10
maxlen-in: 500  # if input length  > maxlen_in, batchsize is automatically reduced
maxlen-out: 150 # if output length > maxlen_out, batchsize is automatically reduced

# optimization related
sortagrad: 0 # Feed samples from shortest to longest ; -1: enabled for all epochs, 0: disabled, other: enabled for 'other' epochs
opt: adadelta
epochs: 30
patience: 3

# scheduled sampling option
sampling-probability: 0.0

# Extra
dropout-rate: 0.1
dropout-rate-decoder: 0.1
weight-decay: 0.0001
# report-interval-iters: 1
